### ISSUE TITLE
Need the color codes for the  website's look

### ISSUE THREAD

**Issue by ashfaqnisar** [Ezerka/Next-JS-Website#2]
We need to know the color codes of black & red to work in the website

**Comment by vamshikrishnaginna** [comment]
Red color code: #ed1c24

**Comment by vamshikrishnaginna** [comment]
Black color code: #000000

**Comment by ashfaqnisar** [comment]
Coll ra vamshi

**Comment by ashfaqnisar** [comment]
This has already been done in the website
