### ISSUE TITLE
Need favicon for the website

### ISSUE THREAD

**Issue by ashfaqnisar** [Ezerka/Next-JS-Website#3]
**Describe about the thing which you require**
We need the ezerka favicon for the website, I think you should already have this, can you share it here

**Comment by ashfaqnisar** [comment]
The resolution is 16*16

**Comment by vamshikrishnaginna** [comment]
[Ezerka_Favicon.zip](https://github.com/Ezerka/Next-JS-Website/files/4545669/Ezerka_Favicon.zip)

**Comment by vamshikrishnaginna** [comment]
If everything seems to be ok, close the issue.

**Comment by ashfaqnisar** [comment]
I will add this to the website and close it
