### ISSUE TITLE
Need the ezerka logo

### ISSUE THREAD

**Issue by ashfaqnisar** [Ezerka/Next-JS-Website#4]
**Describe about the thing which you require**
We need the ezerka logo for the website,  with the resolution 241*74 but also provide the actual logo with the actual dimensions

**Comment by ashfaqnisar** [comment]
Also, we need the white text and black text logo

**Comment by vamshikrishnaginna** [comment]
[Logo.zip](https://github.com/Ezerka/Next-JS-Website/files/4545676/Logo.zip)

**Comment by vamshikrishnaginna** [comment]
Uploaded the zip file which contains both png and svg files.

**Comment by ashfaqnisar** [comment]
got it ra vamshi
